// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: definitions.sql

package database

import (
	"context"
)

const createDefinition = `-- name: CreateDefinition :one
INSERT INTO definitions (id, word_id, pos_id, "definition")
VALUES (
    DEFAULT,
    $1,
    $2,
    $3
)
RETURNING id, word_id, pos_id, definition
`

type CreateDefinitionParams struct {
	WordID     int32
	PosID      int32
	Definition string
}

func (q *Queries) CreateDefinition(ctx context.Context, arg CreateDefinitionParams) (Definition, error) {
	row := q.db.QueryRowContext(ctx, createDefinition, arg.WordID, arg.PosID, arg.Definition)
	var i Definition
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.PosID,
		&i.Definition,
	)
	return i, err
}
