// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Definition struct {
	ID         int32
	WordID     int32
	PosID      int32
	Definition string
}

type PartsOfSpeech struct {
	ID  int32
	Pos string
}

type Word struct {
	ID   int32
	Word string
}
