// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pos.sql

package database

import (
	"context"
)

const createPos = `-- name: CreatePos :one
INSERT INTO parts_of_speech (id, pos)
VALUES (
    DEFAULT, 
    $1
) 
RETURNING id, pos
`

func (q *Queries) CreatePos(ctx context.Context, pos string) (PartsOfSpeech, error) {
	row := q.db.QueryRowContext(ctx, createPos, pos)
	var i PartsOfSpeech
	err := row.Scan(&i.ID, &i.Pos)
	return i, err
}

const getIDByPos = `-- name: GetIDByPos :one
SELECT id FROM parts_of_speech WHERE pos=$1
`

func (q *Queries) GetIDByPos(ctx context.Context, pos string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getIDByPos, pos)
	var id int32
	err := row.Scan(&id)
	return id, err
}
