// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pos.sql

package database

import (
	"context"
)

const createPos = `-- name: CreatePos :one
INSERT INTO parts_of_speech (id, pos)
VALUES (
    DEFAULT, 
    $1
) 
RETURNING id, pos
`

func (q *Queries) CreatePos(ctx context.Context, pos string) (PartsOfSpeech, error) {
	row := q.db.QueryRowContext(ctx, createPos, pos)
	var i PartsOfSpeech
	err := row.Scan(&i.ID, &i.Pos)
	return i, err
}
