// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: words.sql

package database

import (
	"context"
)

const createWord = `-- name: CreateWord :one
INSERT INTO words (id, word)
VALUES (
    DEFAULT, 
    $1
) 
RETURNING id, word
`

func (q *Queries) CreateWord(ctx context.Context, word string) (Word, error) {
	row := q.db.QueryRowContext(ctx, createWord, word)
	var i Word
	err := row.Scan(&i.ID, &i.Word)
	return i, err
}
